### ISSUE TITLE
Module troubleshooting

### ISSUE THREAD

**Issue by gjerdery** [lib-uoguelph-ca/Omeka-S-module-GroupEdit#1]
Hi, I've recently installed GroupEdit as a companion to Group, which I already had set up on my v 1.3.0 install. I'm not seeing any change in behavior following installation of GroupEdit, and am not sure where to start with troubleshooting.

**Comment by doana** [comment]
Hi, 

Sorry, I haven't looked at this since August of last year. Obviously, I need to work on the documentation a bit. We're not actually using this code (or even omeka-s at this point) so it hasn't been a priority. 

Part of this might be because there was a bug (which I've just fixed and pushed to the master branch), but also because the documentation isn't clear what this should do. 

This module only really makes a difference for Author users. It grants Authors edit rights for items that belong to groups that they also have membership in. 

To see this at work:

1. Create a group
2. Create two Author users, we'll call them user1 and user2, each in the group
3. Create an item set, give the item set the same group. Make sure the item set is set to 'open'.
4. As user1, create an item in the item set
5. Log in as user2
6. Note that the user2 is able to edit user1's item created in step 4

Hope that helps. 
-Adam

**Comment by gjerdery** [comment]
Thanks Adam,
 That bugfix resolved the issue for me!

Ryan

**Comment by doana** [comment]
Great!
-A
